trigger:
  branches:
    include:
      - master
    exclude:
      - develop
      - release-candidate
      - CliArgumentParser-1.1
  paths:
    include:
      - src
#     exclude:
#       - script/*
#       - libs/*
#       - devops/*
#
schedules:
  - cron: "0 12 * * 0"
    displayName: Weekly Sunday build
    branches:
      include:
        - master

pool:
  vmImage: "ubuntu-latest"

parameters:
  - name: MajorVersion
    displayName: "Major Version"
    default: 1
  - name: MinorVersion
    displayName: "Minor Version"
    default: 1
  - name: authors
    displayName: "Names of authors of the target package"
    default: "FG"
  - name: company
    displayName: "Company that produces the target package"
    default: "Innova Solutions"
  - name: copyright
    displayName: "Copyright"
    default: "FG 2022"

  - name: PublishPackage
    displayName: "Publish Package to Nuget.Org"
    type: boolean
    default: False

variables:
  buildConfiguration: "Release"
  targetFramework: "6.x"
  nugetVersion: ${{ parameters.MajorVersion }}.${{ parameters.MinorVersion }}.$(Build.BuildId)

steps:
  ##### use the right version of .Net core
  - task: UseDotNet@2
    displayName: Use .NET target version
    inputs:
      packageType: "sdk"
      version: $(targetFramework)

  - script: |
      echo "Build ID      => $(Build.BuildId)"
      echo "Build Number  => $(Build.BuildNumber)"
      dotnet tool install --global dotnet-reportgenerator-globaltool
    displayName: "Install ReportGenerator tool"

  - template: .\devops\templates\dotnet-package-pack.yaml
    parameters:
      projPath: src/CliArgumentParser
      projName: CliArgumentParser
      MajorVersion: ${{ parameters.MajorVersion }}
      MinorVersion: ${{ parameters.MinorVersion }}
      buildNumber: $(Build.BuildId)

  - template: .\devops\templates\dotnet-build.yaml
    parameters:
      projPath: src/CliArgumentParser.Tests
      projName: CliArgumentParser.Tests
      publishRequired: false

  ############################## TEST #################################
  - template: .\devops\templates\dotnet-test.yaml
    parameters:
      projPath: src/CliArgumentParser.Tests
      projName: CliArgumentParser.Tests

  ############################## PUBLISH DROP #################################
  - task: PublishBuildArtifacts@1
    displayName: publish artifacts
    inputs:
      PathtoPublish: "$(Build.ArtifactStagingDirectory)"
      ArtifactName: "drop"
      publishLocation: "Container"

  - task: DotNetCoreCLI@2
    displayName: Push
    inputs:
      command: "push"
      packagesToPush: "$(Build.ArtifactStagingDirectory)/*.nupkg"
      nuGetFeedType: "external"
      publishFeedCredentials: "Nuget.org"
      allowPackageConflicts: true
    condition: eq(${{ parameters.PublishPackage }}, true)
