trigger:
  branches:
    include:
      - master
    exclude:
      - develop
      - release-candidate
      - CliArgumentParser-1.1
  paths:
    include:
      - src
#     exclude:
#       - script/*
#       - libs/*
#       - devops/*
#
schedules:
  - cron: "0 12 * * 0"
    displayName: Weekly Sunday build
    branches:
      include:
        - master

pool:
  vmImage: "ubuntu-latest"

parameters:
  - name: MajorVersion
    displayName: "Major Version"
    default: 1
  - name: MinorVersion
    displayName: "Minor Version"
    default: 2
  - name: authors
    displayName: "Names of authors of the target package"
    default: "FG"
  - name: company
    displayName: "Company that produces the target package"
    default: "Innova Solutions"
  - name: copyright
    displayName: "Copyright"
    default: "FG 2022"
  - name: PublishPackage
    displayName: "Publish Package to Nuget.Org"
    type: boolean
    default: False
  - name: NugetApiKey
    displayName: "APIKEY to Publish Package on Nuget.Org"
    default: "set here your Nuget Api Key"

variables:
  buildConfiguration: Release
  targetFramework: "6.x"
  nugetVersion: ${{ parameters.MajorVersion }}.${{ parameters.MinorVersion }}.$(Build.BuildId)
  testReportFileName: cobertura.xml

steps:
  ##### use the right version of .Net core
  - task: UseDotNet@2
    displayName: Use .NET target version
    inputs:
      packageType: "sdk"
      version: $(targetFramework)

  - task: NuGetToolInstaller@1
    displayName: "Use Nuget.exe"
    inputs:
      checkLatest: true

  - template: .\devops\templates\dotnet-tool-install-coverlet.yaml

  - task: SonarCloudPrepare@1
    displayName: "Prepare analysis on SonarCloud"
    inputs:
      SonarCloud: "SonarQubeCloud"
      organization: "fgaravaglia"
      scannerMode: "MSBuild"
      projectKey: "fgaravaglia_CLIArgumentsParser"
      projectName: "CLIArgumentsParser"
      projectVersion: "${{ parameters.MajorVersion }}.${{ parameters.MinorVersion }}"
      extraProperties: |
        # Additional properties that will be passed to the scanner, Put one key=value per line, example:
        sonar.exclusions=**/obj/**,**/*.dll,**/CliArgumentParser.Tests/**,**/CLIArgumentsParser.Tests/**/*.cs
        sonar.verbose=true
        sonar.cs.opencover.reportsPaths=./TestResults/opencover.xml

  - template: .\devops\templates\dotnet-package-pack.yaml
    parameters:
      projPath: src/CliArgumentParser
      projName: CliArgumentParser
      MajorVersion: ${{ parameters.MajorVersion }}
      MinorVersion: ${{ parameters.MinorVersion }}
      buildNumber: $(Build.BuildId)

  - template: .\devops\templates\dotnet-build.yaml
    parameters:
      projPath: src/CliArgumentParser.Tests
      projName: CliArgumentParser.Tests
      publishRequired: false

  ############################## TEST #################################
  - template: .\devops\templates\dotnet-test.yaml
    parameters:
      projPath: src/CliArgumentParser.Tests
      projName: CliArgumentParser.Tests
      reportOutputFormat: Cobertura

  - task: SonarCloudAnalyze@1
    displayName: "Run Sonar Cloud Analysis"

  - task: SonarCloudPublish@1
    displayName: "Publish Sonar Cloud Analysis"
    inputs:
      pollingTimeoutSec: "300"

  ############################## PUBLISH DROP #################################
  - task: PublishBuildArtifacts@1
    displayName: publish artifacts
    inputs:
      PathtoPublish: "$(Build.ArtifactStagingDirectory)"
      ArtifactName: "drop"
      publishLocation: "Container"

  - task: DotNetCoreCLI@2
    displayName: Push to Nuget.org
    inputs:
      command: "custom"
      custom: nuget
      arguments: >
        push $(Build.ArtifactStagingDirectory)/CliArgumentParser.*.nupkg
        -s https://api.nuget.org/v3/index.json
        -k ${{ parameters.NugetApiKey }}
    condition: eq(${{ parameters.PublishPackage }}, true)
