parameters:
  - name: projPath
    default: ""
  - name: projName
    displayName: "name of csProj file (without extension)"
    default: ""

steps:
  # Plese notice that coverlet package generates a predefined file: .\TestResults\{guid}\coverage.cobertura.xml 
  # for additional info see: https://medium.com/geekculture/net-6-tests-coverge-with-coverlet-b6fe2605ee19  
  - task: DotNetCoreCLI@2
    displayName: "dotnet test Cobertura - ${{ parameters.projName }}"
    inputs:
      command: test
      projects: "${{ parameters.projPath }}/${{ parameters.projName }}.csproj"
      arguments: '--logger trx --configuration Debug --collect "XPlat Code coverage" -- RunConfiguration.DisableAppDomain=true'
      testRunTitle: ${{ parameters.projName }}

  - task: CopyFiles@2
    displayName: "Copy Test results to staging folder"
    inputs:
      contents: '$(Agent.TempDirectory)/TestResults/**'
      targetFolder: $(Build.ArtifactStagingDirectory)/TestResults

  - script: |
      reportgenerator -reports:$(Agent.TempDirectory)/**/coverage.cobertura.xml -targetdir:$(Build.SourcesDirectory)/reports/coverlet -reporttypes:"Cobertura"
    displayName: "Create Cobertura report"

  - task: PublishCodeCoverageResults@1
    displayName: "Publish code coverage Cobertura"
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: "$(Build.SourcesDirectory)/reports/coverlet/Cobertura.xml"
  
  - task: CopyFiles@2
    displayName: "Copy Report to staging folder"
    inputs:
      contents: '$(Agent.TempDirectory)/reports'
      targetFolder: $(Build.ArtifactStagingDirectory)/reports
